import { Box, Button, useColorMode } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
  const { colorMode, toggleColorMode } = useColorMode()

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Box
          w='100%'
          h='50px'
          bgGradient='linear(to-r, blue.400, blue.600, blue.500, blue.400, blue.600, blue.500, blue.400, blue.600, blue.500, blue.400, blue.600, blue.500, blue.400, blue.600, blue.500, blue.400, blue.600, blue.500, blue.400, blue.600, blue.500, blue.400, blue.600, blue.500, blue.400, blue.600, blue.500, blue.400, blue.600, blue.500, blue.400, blue.600, blue.500, blue.400, blue.600, blue.500, blue.400, blue.600, blue.500, blue.400, blue.600, blue.500, blue.400, blue.600, blue.500, blue.400, blue.600, blue.500, blue.400, blue.600, blue.500, blue.400, blue.600, blue.500, blue.400, blue.600, blue.500, blue.400, blue.600, blue.500, blue.400, blue.600, blue.500, blue.400, blue.600, blue.500, blue.400, blue.600, blue.500, blue.400, blue.600, blue.500, blue.400, blue.600, blue.500, blue.400, blue.600, blue.500)'
        />

        <Button onClick={toggleColorMode}>
          Toggle {colorMode === 'light' ? 'Dark' : 'Light'}
        </Button>
      </main>

      <footer>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'>
          Powered by{' '}
          <span>
            <Image
              src='/vercel.svg'
              alt='Vercel Logo'
              width={72}
              height={16}
            />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
